---
verbose: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate_no_variables
      - id: terraform_validate_with_variables
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.6
    hooks:
      - id: forbid-tabs
